### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by sahara101** [Akasiek/Random-Plex-Movie#12]
Hi!

Py is working great, thanks!

Sorry for posting here. I am trying to integrate plex with node-red for random unwatched movie playback.
I cannot for the life of me understand how I need to define the API call in order to start a playback....can you help me? I am using an Apple TV.

Thanks!

**Comment by Akasiek** [comment]
I'm sorry but I'm not familiar with Node-RED and I do not know how the Plex API implementation works there.
