### ISSUE TITLE
Windows installation cannot find Chrome install

### ISSUE THREAD

**Issue by ejach** [Akasiek/Random-Plex-Movie#3]
Hello,
Upon installing I am shown this error:
```
File "randomPlexMovie.py", line 71, in <module>
    eel.start('index.html',
  File "/usr/local/lib/python3.8/dist-packages/eel/__init__.py", line 158, in start
    show(*start_urls)
  File "/usr/local/lib/python3.8/dist-packages/eel/__init__.py", line 186, in show
    brw.open(start_urls, _start_args)
  File "/usr/local/lib/python3.8/dist-packages/eel/browsers.py", line 65, in open
    raise EnvironmentError("Can't find %s installation" % browser_module.name)
OSError: Can't find Google Chrome/Chromium installation
```
I had to specify the correct path using the `eel.browsers` module by adding:
`eel.browsers.set_path('chrome', '/mnt/c/Program Files/Google/Chrome/Application/chrome.exe')`

This fix is evident in PR #4 

Thanks!

**Comment by Akasiek** [comment]
Thank you for addressing this issue. I was not aware of it and I will add this comment lines in the next commit.

**Comment by ejach** [comment]
> Thank you for addressing this issue. I was not aware of it and I will add this comment lines in the next commit.

I just sent a PR for this, edit it as you will.

Thanks for the reply!

**Comment by Akasiek** [comment]
Yep. I just merged it

**Comment by ejach** [comment]
> Yep. I just merged it

I also screwed up and exposed my local media server in [this](https://github.com/Akasiek/Random-Plex-Movie/pull/4/commits/ff62ece7514382c8a1dc152047f246a5f436dea6) pull request in the .ini file.

I am still learning about git/github, are you able to delete this? If not, I already changed the keys, I am just referencing my IP address.

Sorry about that!

**Comment by Akasiek** [comment]
I will try to delete it

**Comment by Akasiek** [comment]
Ok. There is only one way to do it. https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

**Comment by ejach** [comment]
> Ok. There is only one way to do it. https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

Alright, I sent in a support ticket.

I will update this thread when they reply.

Thanks for the help 👍

**Comment by ejach** [comment]
@Akasiek 

GitHub support finally got back to me, here is what they said:

> Hi Evan,
> 
> Thanks for reaching out!
> 
> For privacy and security reasons, only an admin of that repository can request that we delete this pull request. If you're able to get in touch with an admin directly, the quickest way to resolve this would be for them to write in requesting that we delete the pull request. They can reach out to us directly, or in a reply to this email if you'd like to CC them.
> 
> If you're not able to contact an admin of that repository, please take a look at the following article for information about how to submit a content removal request:
> 
> https://docs.github.com/github/site-policy/submitting-content-removal-requests
> 
> Feel free to reach out if you have any additional questions about this!
> 
> Regards
> Peter
> GitHub Support

So I guess that you would have to make the request 🤦‍♂️
If this is something that you do not wish to do, I understand.
Again, I already reset my API key so it is just my public IP that is at stake.
Thanks.

**Comment by Akasiek** [comment]
I send the request. I'll keep you updated

**Comment by ejach** [comment]
> I send the request. I'll keep you updated

I appreciate it!

**Comment by Akasiek** [comment]
The commit has been deleted.

**Comment by ejach** [comment]
Thank you so much for your help!
